title: Linky
subheads:
    - "A Linktree-esque Jekyll theme, compatible with Sveltia CMS."

email: paul@roub.net
description: >-
    A Linktree-esque Jekyll theme, compatible with Sveltia CMS.
baseurl: ""
url: "https://linky.roub.net"
github_username: paulroub

plausible_io: linky.roub.net

# Build settings
theme: jekyll-theme-linky
plugins:
    - jekyll-feed

exclude:
    - VERSION
    - bin
    - linky.gemspec
    - netlify.toml
    - package*.json
    - linky-template

linky:
    body_background: "#030303"
    body_foreground: "#F0F0F0"
    button_background: "#f16293"
    social_button_color: "#ffffff"
    add_rel_me_links: true # add <link rel="me"> tags for each social media account

collections:
    links:
        title: "My linx!"

# tell the jekyll-feed plugin to include the links collection
feed:
    collections:
        - links
